### ISSUE TITLE
Add support for Swap

### ISSUE THREAD

**Issue by tmoon** [terra-project/terra-js#1]
It would be great to have support for Swap and the conversion rates for the swaps @YunSuk-Yeo

**Comment by YunSuk-Yeo** [comment]
For the swap rate, you can query with lcd. 

1) Get oracle price with `/oracle/denoms/{denom}/price`
2) Simulate swap `/market/swap`

**buildSwap is patched**

**Comment by tmoon** [comment]
Thanks!
