### ISSUE TITLE
Potential Issues with build script

### ISSUE THREAD

**Issue by tmoon** [terra-project/terra-js#2]
Hey @YunSuk-Yeo we tried running this following script:

```
const terra = require('@terra-money/core');

const mnemonic = terra.generateMnemonic();
console.log(mnemonic)
```
as follows:
1. `npm init`
2. save the script above as `index.js`
3. ran `npm i @terra-money/core`

while it installed the package in node modules for some reason it did not build properly inside the `/core` folder. We had to manually run `npm install && npm run build` to build

Not sure what is happening

**Comment by hanjukim** [comment]
I can't reproduce this problem with `npm i` nor `yarn add` what is your node.js and npm version?
