### ISSUE TITLE
How to get balance?

### ISSUE THREAD

**Issue by oleiba** [terra-project/terra-js#7]
Hi, it seems that there isn't any method to get the balance of a given account address.
Is there one and I'm missing something, or is there another resource I get can get it from? (programmatically, of course)

Same question regarding getting the list of past transactions which a given account was involved in...

**Comment by YunSuk-Yeo** [comment]
@oleiba 
terra-js has no feature for querying on chain data. To get those information, you have to use light-client (lcd). Here is [doc](https://docs.terra.money/docs/node-light-client#docsNav) for light client rest-server. 

To get the balance, you can use `/auth/accounts/{address}` or `/bank/balance/{address}` endpoints
https://lcd.terra.dev/auth/accounts/terra1rf9xakxf97a49qa5svsf7yypjswzkutqfclur8 or https://lcd.terra.dev/bank/balances/terra1rf9xakxf97a49qa5svsf7yypjswzkutqfclur8.

To query past transaction, you can use `/txs` endpoint 
Ex)
https://lcd.terra.dev/txs?tx.height=10000
https://lcd.terra.dev/txs?message.sender=terra1rf9xakxf97a49qa5svsf7yypjswzkutqfclur8
https://lcd.terra.dev/txs?message.recipient=terra1rf9xakxf97a49qa5svsf7yypjswzkutqfclur8
https://lcd.terra.dev/txs?message.sender=terra1rf9xakxf97a49qa5svsf7yypjswzkutqfclur8&tx.height=1329

**Comment by YunSuk-Yeo** [comment]
And we will add new features for querying on-chain data(sequence, account number, balance and so on) in terra-js with registered lcd.
